# Generated by Django 5.0.7 on 2024-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(help_text='425x425px recommended', upload_to='profile_pics'),
        ),
    ]
